# theme: jekyll-theme-slate
# theme: carte-noire
# theme: jekyll-theme-leap-day
# theme: blackdoc
theme: midnight
# theme: midnight
# theme: naringu
# , skinny-bones-jekyll, solar-theme-jekyll
title: Welcome to BethZ's webpage!
description: This is a place to find all of BethZ's current projects.
