# theme: jekyll-theme-slate
# theme: carte-noire
theme: jekyll-theme-leap-day
# theme: jekyll-theme-slate
title: Welcome to BethZ's webpage!
description: This is a place to find all of BethZ's current projects.
